- hosts: master
  become: true
  connection: local

  roles:
    - {role: 'install-nginx', tags: 'setup'}
    - {role: 'install-certbot', tags: 'setup'}
    - {role: 'add-www-user', tags: 'setup'}
    - {role: 'install-php', tags: 'setup'}
    - {role: 'install-mysql', tags: 'setup'}
