- hosts: master
  become: true
  connection: local

  roles:
    - {role: 'install-nginx', tags: 'setup'}
    - {role: 'install-certbot', tags: 'setup'}
    - {role: 'add-www-user', tags: 'setup'}
    - {role: 'install-php', tags: 'setup'}
    - {role: 'install-mysql', tags: 'setup'}
    - {role: 'install-node', tags: 'setup'}
    - {role: 'create-database', tags: 'new-app'}
    - {role: 'create-database-user', tags: 'new-app'}
    - {role: 'create-host', tags: 'new-app'}
    - {role: 'add-ssh-key', tags: 'add-ssh-key'}
