- name: migrate database

- name: config env
  # mysql root password
  # playbooks wd

- name: register local server & site

- name: register admin

- name: generate ssh key 'worker@pilot.example.com'
