- name: add gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add source
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/{{ node_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/{{ node_version }} {{ ansible_distribution_release }} main"

- name: install package
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes
    install_recommends: no