- name: create app directory
  file:
    path: "{{ app_directory }}"
    state: directory
    recurse: yes
  become_user: "{{ www_user }}"

- name: copy default index
  template:
    src: index.php.j2
    dest: "{{ app_directory }}/index.php"
  become_user: "{{ www_user }}"

- name: add http host
  template:
    src: host-http.j2
    dest: /etc/nginx/sites-available/{{ app_hostname }}-http

- name: enable http host
  file:
    src: /etc/nginx/sites-available/{{ app_hostname }}-http
    dest: /etc/nginx/sites-enabled/{{ app_hostname }}-http
    state: link

- name: reload nginx to active new host
  service:
    name: nginx
    state: restarted

- name: create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /var/www/letsencrypt -m {{ certbot_email }} --agree-tos -d {{ app_hostname }}
  args:
    creates: /etc/letsencrypt/live/{{ app_hostname }}

- name: add https host
  template:
    src: host-https.j2
    dest: /etc/nginx/sites-available/{{ app_hostname }}-https

- name: enable https host
  file:
    src: /etc/nginx/sites-available/{{ app_hostname }}-https
    dest: /etc/nginx/sites-enabled/{{ app_hostname }}-https
    state: link

- name: reload nginx to active new host
  service:
    name: nginx
    state: restarted

- name: reload nginx to active new host
  service:
    name: nginx
    state: restarted

- name: add letsencrypt's cronjob for cert renewal
  cron:
    name: Letsencrypt renewal for {{ app_hostname }}
    special_time: weekly
    job: letsencrypt --renew certonly -n --webroot -w /var/www/letsencrypt -m {{ certbot_email }} --agree-tos -d {{ app_hostname }} && service nginx reload
